#!/usr/bin/env python
# -*- coding: utf-8 -*-

# This file is part of captlog.
#
# captlog - Captain's Log (secret diary and notes application)
#
# Written in 2013 by Ricardo Garcia <public@rg3.name>
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along with
# this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

import Tkinter
import ttk
import tkFont
import tkMessageBox
import os.path

lorem_ipsum = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae augue lectus. Curabitur pellentesque ac eros eget imperdiet. Integer tincidunt, metus non cursus tincidunt, justo metus consequat magna, ut suscipit mauris sapien vitae nisl. Aenean tristique leo nec convallis dictum. Mauris dignissim, magna quis fermentum placerat, lorem elit lobortis eros, quis dignissim justo neque et justo. In et fringilla justo, ut congue est. Donec ut volutpat leo. Mauris vitae ipsum at turpis egestas placerat sed pharetra est. Proin lacinia ipsum massa, eget fermentum nulla sollicitudin sit amet.

Ut ac tellus mauris. Mauris erat nunc, fermentum ut convallis vitae, aliquet sit amet elit. Sed justo tortor, malesuada vel nisl non, sodales ultrices tortor. Donec euismod, nibh a luctus sollicitudin, ante justo consequat justo, nec tristique massa nulla condimentum massa. Ut congue porta ornare. Proin vitae enim tortor. Cras adipiscing tellus sapien, eu commodo nunc mollis in. Sed laoreet nunc dolor, vel lacinia nibh adipiscing sit amet. Donec ut dignissim tellus. Mauris lobortis tincidunt pellentesque. Nullam orci velit, volutpat vitae convallis at, interdum et felis. Aenean bibendum et nisi in consectetur. Morbi viverra faucibus eros.

Ut dui nulla, laoreet dapibus elementum sed, vehicula ut leo. Donec eget ultrices justo, ut mollis nisl. Nulla consequat condimentum sapien, a elementum odio vulputate nec. In justo massa, accumsan non sapien sed, volutpat dapibus lectus. Nulla facilisi. Aenean a vulputate nibh. Nulla eget neque lacus. Proin lectus leo, rhoncus non imperdiet sit amet, lacinia et sapien. Aliquam quis accumsan nisi, a luctus tortor.

Duis accumsan quis lectus at malesuada. Mauris elit nisi, fringilla ut fermentum sed, scelerisque vitae velit. Ut vitae dui lectus. Etiam diam magna, fermentum sit amet lectus at, imperdiet tempor ipsum. Nulla leo velit, venenatis in massa eget, scelerisque hendrerit purus. Nullam facilisis, mauris eu condimentum fermentum, erat erat varius velit, et accumsan tellus mauris id mi. Praesent bibendum sodales tristique.

Maecenas at dictum risus. Duis fermentum feugiat eros at eleifend. Maecenas at sapien ut sem euismod tristique sed eget turpis. Sed in molestie tellus. Sed hendrerit accumsan mattis. Aenean lacus eros, fringilla eu feugiat sit amet, facilisis a turpis. Nam felis eros, elementum at leo sed, convallis ultricies nisl. In accumsan quam purus, ac auctor nisi elementum sit amet. Nunc condimentum nisi neque, ac lobortis risus pellentesque eu. Ut adipiscing, mi sed porttitor blandit, magna massa eleifend nisi, eget faucibus enim ipsum vel mauris. Pellentesque erat quam, convallis et ligula vel, lacinia egestas augue. Fusce porttitor magna non massa fermentum consequat. Integer consectetur vehicula lacus, in venenatis risus iaculis a. Cras ultricies ornare magna in egestas."""

default_padding = 10
expand = { 'sticky': (Tkinter.N, Tkinter.W, Tkinter.E, Tkinter.S) }
vpadexpand = dict({ 'pady': default_padding }, **expand)
hpadexpand = dict({ 'padx': default_padding }, **expand)
padexpand = dict({
    'padx': default_padding,
    'pady': default_padding, },
    **expand )
fullpadexpand = dict({
    'ipadx': default_padding,
    'ipady': default_padding, },
    **padexpand )
image_path = '.'

# Window
root = Tkinter.Tk(className="captlog")
root.title("captlog: The Captain's Log")

new_img = Tkinter.PhotoImage(file=os.path.join(image_path, 'new.png'))
del_img = Tkinter.PhotoImage(file=os.path.join(image_path, 'delete.png'))
save_img = Tkinter.PhotoImage(file=os.path.join(image_path, 'save.png'))
exit_img = Tkinter.PhotoImage(file=os.path.join(image_path, 'exit.png'))

bold_font = tkFont.nametofont("TkDefaultFont").copy()
bold_font.configure(weight='bold')

#
# Widget hierarchy.
#

# Main window frame.
main_frame = ttk.Frame(root)
# Left pane with tabs.
notebook = ttk.Notebook(main_frame)
entries_frame = ttk.Frame(notebook)
bookmarks_frame = ttk.Frame(notebook)
notebook.add(entries_frame, text="Entries")
notebook.add(bookmarks_frame, text="Bookmarks")
# Entries tab.
new_entry_button = ttk.Button(entries_frame, text="New Entry", image=new_img, compound='left')
del_entry_button = ttk.Button(entries_frame, text="Delete Entry", image=del_img, compound='left')
entry_list_frame = ttk.Button(entries_frame)
entry_listbox = Tkinter.Listbox(entry_list_frame, height=24)
for i in [x for x in xrange(1, 30+1)][::-1]:
    entry_listbox.insert('end', 'Entry from 2013-06-%02d' % i)
entry_listbox_sb = ttk.Scrollbar(entry_list_frame, command=entry_listbox.yview)
entry_listbox.configure(yscrollcommand=entry_listbox_sb.set)
# Bookmarks tab.
new_bookmark_button = ttk.Button(bookmarks_frame, text="New Bookmark", image=new_img, compound='left')
del_bookmark_button = ttk.Button(bookmarks_frame, text="Delete Bookmark", image=del_img, compound='left')
bookmark_list_frame = ttk.Button(bookmarks_frame)
bookmark_listbox = Tkinter.Listbox(bookmark_list_frame, height=24)
for i in xrange(1, 30+1):
    bookmark_listbox.insert('end', 'Bookmark number %s' % i)
bookmark_listbox_sb = ttk.Scrollbar(bookmark_list_frame, command=bookmark_listbox.yview)
bookmark_listbox.configure(yscrollcommand=bookmark_listbox_sb.set)
notebook_sep = ttk.Separator(main_frame, orient='vertical')
# Right pane displaying an entry.
entry_display_frame = ttk.Frame(main_frame)
ctime_label = ttk.Label(entry_display_frame, text='Created on:', font=bold_font)
ctime_value_label = ttk.Label(entry_display_frame, text='2013-06-26T20:15:00Z')
mtime_label = ttk.Label(entry_display_frame, text='Modified on:', font=bold_font)
mtime_value_label = ttk.Label(entry_display_frame, text='2013-06-26T20:16:01Z')
save_button = ttk.Button(entry_display_frame, text='Save Entry', image=save_img, compound='left')
save_button.configure(state='disabled')
entry_text_sep = ttk.Separator(entry_display_frame, orient='horizontal')
entry_text_frame = ttk.Frame(entry_display_frame)
entry_text = Tkinter.Text(entry_text_frame, width=80, wrap='word', relief='solid')
entry_text.insert("0.0", lorem_ipsum)
entry_text_sb = ttk.Scrollbar(entry_text_frame, command=entry_text.yview)
entry_text.configure(yscrollcommand=entry_text_sb.set)
# Exit button.
exit_button = ttk.Button(main_frame, text="Exit Program", command=root.destroy, image=exit_img, compound='left')

#
# Widget positioning.
#

# Main window frame.
root.columnconfigure(0, weight=1)
root.rowconfigure(0, weight=1)
main_frame.grid(row=0, column=0, **padexpand)
main_frame.columnconfigure(2, weight=1)
main_frame.rowconfigure(0, weight=1)
# Left pane with tabs.
notebook.grid(row=0, column=0, **expand)
# Entries tab.
entries_frame.columnconfigure(0, weight=1)
entries_frame.columnconfigure(1, weight=1)
entries_frame.rowconfigure(1, weight=1)
new_entry_button.grid(row=0, column=0, **padexpand)
del_entry_button.grid(row=0, column=1, **padexpand)
entry_list_frame.grid(row=1, column=0, columnspan=2, **expand)
entry_list_frame.columnconfigure(0, weight=1)
entry_list_frame.rowconfigure(0, weight=1)
entry_listbox.grid(row=0, column=0, **expand)
entry_listbox_sb.grid(row=0, column=1, sticky=(Tkinter.N, Tkinter.S))
# Bookmarks tab.
bookmarks_frame.columnconfigure(0, weight=1)
bookmarks_frame.columnconfigure(1, weight=1)
bookmarks_frame.rowconfigure(1, weight=1)
new_bookmark_button.grid(row=0, column=0, **padexpand)
del_bookmark_button.grid(row=0, column=1, **padexpand)
bookmark_list_frame.grid(row=1, column=0, columnspan=2, **expand)
bookmark_list_frame.columnconfigure(0, weight=1)
bookmark_list_frame.rowconfigure(0, weight=1)
bookmark_listbox.grid(row=0, column=0, **expand)
bookmark_listbox_sb.grid(row=0, column=1, sticky=(Tkinter.N, Tkinter.S))
notebook_sep.grid(row=0, column=1, **hpadexpand)
# Right pane displaying an entry.
entry_display_frame.grid(row=0, column=2, **expand)
entry_display_frame.columnconfigure(1, weight=1)
entry_display_frame.rowconfigure(2, weight=1)
ctime_label.grid(row=0, column=0, sticky=Tkinter.W)
ctime_value_label.grid(row=0, column=1, sticky=Tkinter.W)
mtime_label.grid(row=1, column=0, sticky=Tkinter.W)
mtime_value_label.grid(row=1, column=1, sticky=Tkinter.W)
save_button.grid(row=0, column=2, rowspan=2, **expand)
entry_text_frame.grid(row=2, column=0, columnspan=3, pady=(default_padding, 0), **expand)
entry_text_frame.columnconfigure(0, weight=1)
entry_text_frame.rowconfigure(0, weight=1)
entry_text.grid(row=0, column=0, **expand)
entry_text_sb.grid(row=0, column=1, **expand)
# Exit button.
exit_button.grid(row=1, column=0, columnspan=3, pady=(default_padding, 0), sticky=Tkinter.E)

s = ttk.Style()
#s.theme_use('alt')
s.theme_use('clam')

#answer = tkMessageBox.askyesno(
#    title="Sooperimportant Question",
#    message="Is 'no' the answer to this question?")
#print 'Answer: %r' % answer

root.mainloop()

